// Ad content — billboard, car wrap, and Caltrain ads
// Replace ad bodies with Google AdMob / Google Ads SDK calls later.
// For now, a random selector picks from this pool.

export interface AdContent {
  id: string
  brand: string
  headline: string
  subline?: string
  body?: string       // 1-2 word tagline
  primaryColor: string
  secondaryColor: string
  textColor: string
  accentColor: string
  style: 'tech' | 'food' | 'transit' | 'city' | 'fashion' | 'entertainment' | 'health'
}

// ── Billboard ads (SF-area style) ──────────────────────────────────────────────
export const BILLBOARD_ADS: AdContent[] = [
  {
    id: 'lime-scooter',
    brand: 'Lime',
    headline: 'UNLOCK THE CITY',
    subline: 'E-scooters available everywhere',
    primaryColor: '#00d900',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#b8ff00',
    style: 'transit',
  },
  {
    id: 'lyft-ride',
    brand: 'Lyft',
    headline: 'DRIVE OR RIDE',
    subline: 'Your city, your way',
    primaryColor: '#ff71ce',
    secondaryColor: '#1a0033',
    textColor: '#ffffff',
    accentColor: '#ff99ee',
    style: 'transit',
  },
  {
    id: 'golden-gate',
    brand: 'SFParks',
    headline: 'GOLDEN GATE PARK',
    subline: '60 acres of freedom',
    primaryColor: '#0055aa',
    secondaryColor: '#ff6600',
    textColor: '#ffffff',
    accentColor: '#ff9900',
    style: 'city',
  },
  {
    id: 'salesforce-cloud',
    brand: 'Salesforce',
    headline: 'AI + CRM = GROWTH',
    subline: 'salesforce.com',
    primaryColor: '#00a1e0',
    secondaryColor: '#001122',
    textColor: '#ffffff',
    accentColor: '#0099cc',
    style: 'tech',
  },
  {
    id: 'uber-eats',
    brand: 'Uber Eats',
    headline: 'DELIVERED IN 30',
    subline: 'Restaurant to door',
    primaryColor: '#06c167',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#00ff77',
    style: 'food',
  },
  {
    id: 'doordash',
    brand: 'DoorDash',
    headline: 'GET IT NOW',
    subline: 'Restaurants near you',
    primaryColor: '#ff3008',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ff6050',
    style: 'food',
  },
  {
    id: 'caltrain-ad',
    brand: 'Caltrain',
    headline: 'SKIP THE DRIVE',
    subline: 'Caltrain · Fast · Frequent',
    primaryColor: '#cc4422',
    secondaryColor: '#ffcc00',
    textColor: '#ffffff',
    accentColor: '#ffdd44',
    style: 'transit',
  },
  {
    id: 'sf-muni',
    brand: 'SFMTA',
    headline: 'MUNI ALL DAY',
    subline: 'Ride Muni · Go anywhere',
    primaryColor: '#aa0000',
    secondaryColor: '#ffcc00',
    textColor: '#ffffff',
    accentColor: '#ffdd00',
    style: 'transit',
  },
  {
    id: 'aireserv',
    brand: 'AirServ',
    headline: 'STAY COOL THIS SUMMER',
    subline: 'HVAC & home services',
    primaryColor: '#0055ff',
    secondaryColor: '#001133',
    textColor: '#ffffff',
    accentColor: '#33aaff',
    style: 'health',
  },
  {
    id: 'mission-checks',
    brand: 'Mission Check',
    headline: 'FREE CHECKING',
    subline: 'No fees. No minimums.',
    primaryColor: '#006633',
    secondaryColor: '#ffdd00',
    textColor: '#ffffff',
    accentColor: '#99ff00',
    style: 'entertainment',
  },
  {
    id: 'bay-broadband',
    brand: 'BayBroadband',
    headline: '1 GIG FIBER',
    subline: 'Fiber to your door',
    primaryColor: '#003366',
    secondaryColor: '#ff6600',
    textColor: '#ffffff',
    accentColor: '#ff8833',
    style: 'tech',
  },
  {
    id: 'sffit-club',
    brand: 'SF Fit Club',
    headline: 'TRANSFORM YOUR BODY',
    subline: 'First month free',
    primaryColor: '#ff3300',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ff6600',
    style: 'health',
  },
  {
    id: 'ocean-beach',
    brand: 'OCEAN BEACH',
    headline: 'SUMMER HOURS',
    subline: 'Open dawn to dusk',
    primaryColor: '#0099cc',
    secondaryColor: '#ffcc00',
    textColor: '#ffffff',
    accentColor: '#00bbff',
    style: 'city',
  },
  {
    id: 'spark-fund',
    brand: 'Spark Fund',
    headline: 'RAISE YOUR SEED',
    subline: 'VC for founders',
    primaryColor: '#6600ff',
    secondaryColor: '#ffdd00',
    textColor: '#ffffff',
    accentColor: '#bb88ff',
    style: 'tech',
  },
  {
    id: 'taco-truck',
    brand: 'Taco Loco',
    headline: 'AUTHENTIC TACOS',
    subline: 'Mission District · Est. 1974',
    primaryColor: '#ff8800',
    secondaryColor: '#cc0000',
    textColor: '#ffffff',
    accentColor: '#ffcc00',
    style: 'food',
  },
  {
    id: 'chase-bank',
    brand: 'Chase',
    headline: 'MAKE YOUR MOVE',
    subline: 'Chase Total Checking',
    primaryColor: '#0055aa',
    secondaryColor: '#ff0000',
    textColor: '#ffffff',
    accentColor: '#0066cc',
    style: 'entertainment',
  },
  {
    id: 'sf-museum',
    brand: 'Exploratorium',
    headline: 'PLAY. DISCOVER. LEARN.',
    subline: 'Exploratorium · SF',
    primaryColor: '#ff6600',
    secondaryColor: '#003366',
    textColor: '#ffffff',
    accentColor: '#ffaa44',
    style: 'city',
  },
  {
    id: 'netflix-sf',
    brand: 'Netflix',
    headline: 'WATCH ANYWHERE',
    subline: 'Stream on all devices',
    primaryColor: '#e50914',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ff2233',
    style: 'entertainment',
  },
  {
    id: 'planet-dhs',
    brand: "Planet Labs",
    headline: 'SEE EARTH DAILY',
    subline: 'Satellite imagery',
    primaryColor: '#00aacc',
    secondaryColor: '#001133',
    textColor: '#ffffff',
    accentColor: '#66ddff',
    style: 'tech',
  },
  {
    id: 'sffd-recruit',
    brand: 'SFFD',
    headline: 'BECOME A FIREFIGHTER',
    subline: 'Join San Francisco Fire',
    primaryColor: '#ff3300',
    secondaryColor: '#ffcc00',
    textColor: '#ffffff',
    accentColor: '#ff6600',
    style: 'city',
  },
]

// ── Vehicle wrap ads ────────────────────────────────────────────────────────────
export const VEHICLE_ADS: AdContent[] = [
  {
    id: 'wrap-lime',
    brand: 'LIME',
    headline: 'UNLOCK THE RIDE',
    primaryColor: '#00d900',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#b8ff00',
    style: 'transit',
  },
  {
    id: 'wrap-uber-eats',
    brand: 'Uber Eats',
    headline: 'DELIVERED FAST',
    primaryColor: '#06c167',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#00ff77',
    style: 'food',
  },
  {
    id: 'wrap-doordash',
    brand: 'DoorDash',
    headline: 'ORDER NOW',
    primaryColor: '#ff3008',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ff6050',
    style: 'food',
  },
  {
    id: 'wrap-stripe',
    brand: 'Stripe',
    headline: 'PAYMENTS ONLINE',
    primaryColor: '#635bff',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#9b99ff',
    style: 'tech',
  },
  {
    id: 'wrap-twitch',
    brand: 'Twitch',
    headline: 'STREAM LIVE',
    primaryColor: '#9146ff',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#bb77ff',
    style: 'entertainment',
  },
  {
    id: 'wrap-grubhub',
    brand: 'Grubhub',
    headline: 'YOUR FOOD',
    primaryColor: '#f63441',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ff6677',
    style: 'food',
  },
  {
    id: 'wrap-sf-cycling',
    brand: 'SF Cycling',
    headline: 'BIKE THE CITY',
    primaryColor: '#ff6600',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#ffaa44',
    style: 'health',
  },
  {
    id: 'wrap-instacart',
    brand: 'Instacart',
    headline: 'GROCERIES FAST',
    primaryColor: '#43b02a',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#66cc44',
    style: 'food',
  },
  {
    id: 'wrap-notion',
    brand: 'Notion',
    headline: 'ORGANIZE ALL',
    primaryColor: '#111111',
    secondaryColor: '#ffffff',
    textColor: '#ffffff',
    accentColor: '#888888',
    style: 'tech',
  },
  {
    id: 'wrap-coinbase',
    brand: 'Coinbase',
    headline: 'TRADE CRYPTO',
    primaryColor: '#0052ff',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#4488ff',
    style: 'tech',
  },
]

// ── Caltrain ad wraps ──────────────────────────────────────────────────────────
export const CALTRAIN_ADS: AdContent[] = [
  {
    id: 'caltrain-salesforce',
    brand: 'Salesforce',
    headline: 'HELLO, TRAINS',
    subline: 'salesforce.com',
    primaryColor: '#00a1e0',
    secondaryColor: '#001122',
    textColor: '#ffffff',
    accentColor: '#0099cc',
    style: 'tech',
  },
  {
    id: 'caltrain-lyft',
    brand: 'Lyft',
    headline: 'CONNECTING BAYS',
    subline: 'lyft.com/caltrain',
    primaryColor: '#ff71ce',
    secondaryColor: '#1a0033',
    textColor: '#ffffff',
    accentColor: '#ff99ee',
    style: 'transit',
  },
  {
    id: 'caltrain-caltrain',
    brand: 'Caltrain',
    headline: 'PENINSULA RAIL',
    subline: 'Caltrain · 505-9900',
    primaryColor: '#cc4422',
    secondaryColor: '#ffdd00',
    textColor: '#ffffff',
    accentColor: '#ffee66',
    style: 'transit',
  },
  {
    id: 'caltrain-uber',
    brand: 'Uber',
    headline: 'FIRST RIDE FREE',
    subline: 'Get Uber · Download now',
    primaryColor: '#000000',
    secondaryColor: '#06c170',
    textColor: '#ffffff',
    accentColor: '#00ff88',
    style: 'transit',
  },
  {
    id: 'caltrain-stripe',
    brand: 'Stripe',
    headline: 'SF HQ',
    subline: 'stripe.com/careers',
    primaryColor: '#635bff',
    secondaryColor: '#111111',
    textColor: '#ffffff',
    accentColor: '#9b99ff',
    style: 'tech',
  },
]
